export const CURRENCY_SYMBOLS: Record<string, string> = {
  AED: 'د.إ',
  AFN: '؋',
  ALL: 'L',
  AMD: '֏',
  ANG: 'ƒ',
  AOA: 'Kz',
  ARS: 'ARS$',
  AUD: 'A$',
  AWG: 'Afl',
  AZN: '₼',
  BAM: 'KM',
  BBD: 'Bds$',
  BDT: '৳',
  BGN: 'лв',
  BHD: '.د.ب',
  BIF: 'FBu',
  BMD: 'BD$',
  BND: 'B$',
  BOB: 'Bs.',
  BRL: 'R$',
  BSD: 'B$',
  BTN: 'Nu.',
  BWP: 'P',
  BYN: 'Br',
  BZD: 'BZ$',
  CAD: 'C$',
  CDF: 'FC',
  CHF: 'Fr',
  CLP: 'CLP$',
  CNY: '¥',
  COP: 'COP$',
  CRC: '₡',
  CUP: 'CUP$',
  CVE: 'CV$',
  CZK: 'Kč',
  DJF: 'Fdj',
  DKK: 'kr',
  DOP: 'RD$',
  DZD: 'د.ج',
  EGP: 'E£',
  ERN: 'Nfk',
  ETB: 'Br',
  EUR: '€',
  FJD: '$',
  FKP: '£',
  GBP: '£',
  GEL: '₾',
  GHS: 'GH₵',
  GIP: '£',
  GMD: 'D',
  GNF: 'FG',
  GTQ: 'Q',
  GYD: '$',
  HKD: 'HK$',
  HNL: 'L',
  HRK: 'kn',
  HTG: 'G',
  HUF: 'Ft',
  IDR: 'Rp',
  ILS: '₪',
  INR: '₹',
  IQD: 'د.ع',
  IRR: '﷼',
  ISK: 'kr',
  JMD: 'J$',
  JOD: 'د.أ',
  JPY: '¥',
  KES: 'KSh',
  KGS: 'сом',
  KHR: '៛',
  KMF: 'CF',
  KPW: '₩',
  KRW: '₩',
  KWD: 'د.ك',
  KYD: 'CI$',
  KZT: '₸',
  LAK: '₭',
  LBP: 'L£',
  LKR: 'Rs',
  LRD: 'L$',
  LSL: 'L',
  LYD: 'د.ل',
  MAD: 'د.م.',
  MDL: 'L',
  MGA: 'Ar',
  MKD: 'ден',
  MMK: 'K',
  MNT: '₮',
  MOP: 'P',
  MRU: 'UM',
  MUR: 'Rs',
  MVR: 'Rf',
  MWK: 'MK',
  MXN: 'MXN$',
  MYR: 'RM',
  MZN: 'MT',
  NAD: 'N$',
  NGN: '₦',
  NIO: 'C$',
  NOK: 'kr',
  NPR: 'Rs',
  NZD: 'NZ$',
  OMR: 'ر.ع.',
  PAB: 'B/.',
  PEN: 'S/.',
  PGK: 'K',
  PHP: '₱',
  PKR: '₨',
  PLN: 'zł',
  PYG: '₲',
  QAR: 'ر.ق',
  RON: 'lei',
  RSD: 'дин.',
  RUB: '₽',
  RWF: 'FRw',
  SAR: 'SR',
  SBD: '$',
  SCR: 'SR',
  SDG: 'SDG',
  SEK: 'kr',
  SGD: 'S$',
  SHP: '£',
  SLL: 'Le',
  SOS: 'Sh',
  SRD: '$',
  SSP: '£',
  STN: 'Db',
  SYP: 'LS',
  SZL: 'L',
  THB: '฿',
  TJS: 'SM',
  TMT: 'T',
  TND: 'د.ت',
  TOP: 'T$',
  TRY: '₺',
  TTD: '$',
  TWD: 'NT$',
  TZS: 'TSh',
  UAH: '₴',
  UGX: 'USh',
  USD: '$',
  UYU: '$',
  UZS: "so'm",
  VES: 'Bs.S',
  VND: '₫',
  VUV: 'VT',
  WST: 'WS$',
  XAF: 'FCFA',
  XCD: '$',
  XOF: 'CFA',
  XPF: '₣',
  YER: '﷼',
  ZAR: 'R',
  ZMW: 'ZK',
  ZWL: '$',
};

export const ALL_CURRENCIES = [
  { value: 'USD', label: 'USD ($) - US Dollar' },
  { value: 'EUR', label: 'EUR (€) - Euro' },
  { value: 'GBP', label: 'GBP (£) - British Pound' },
  { value: 'NGN', label: 'NGN (₦) - Nigerian Naira' },
  { value: 'PKR', label: 'PKR (₨) - Pakistani Rupee' },
  { value: 'MUR', label: 'MUR (Rs) - Mauritian Rupee' },
  { value: 'GHS', label: 'GHS (GH₵) - Ghanaian Cedi' },
  { value: 'KES', label: 'KES (KSh) - Kenyan Shilling' },
  { value: 'ZAR', label: 'ZAR (R) - South African Rand' },
  { value: 'CAD', label: 'CAD (C$) - Canadian Dollar' },
  { value: 'AUD', label: 'AUD (A$) - Australian Dollar' },
  { value: 'INR', label: 'INR (₹) - Indian Rupee' },
  { value: 'AED', label: 'AED (د.إ) - UAE Dirham' },
  { value: 'SAR', label: 'SAR (SR) - Saudi Riyal' },
  { value: 'JPY', label: 'JPY (¥) - Japanese Yen' },
  { value: 'CNY', label: 'CNY (¥) - Chinese Yuan' },
  { value: 'BRL', label: 'BRL (R$) - Brazilian Real' },
  { value: 'CHF', label: 'CHF (Fr) - Swiss Franc' },
  { value: 'AFN', label: 'AFN (؋) - Afghan Afghani' },
  { value: 'ALL', label: 'ALL (L) - Albanian Lek' },
  { value: 'AMD', label: 'AMD (֏) - Armenian Dram' },
  { value: 'ANG', label: 'ANG (ƒ) - Dutch Guilder' },
  { value: 'AOA', label: 'AOA (Kz) - Angolan Kwanza' },
  { value: 'ARS', label: 'ARS ($) - Argentine Peso' },
  { value: 'AWG', label: 'AWG (Afl) - Aruban Florin' },
  { value: 'AZN', label: 'AZN (₼) - Azerbaijani Manat' },
  { value: 'BAM', label: 'BAM (KM) - Bosnian Mark' },
  { value: 'BBD', label: 'BBD ($) - Barbadian Dollar' },
  { value: 'BDT', label: 'BDT (৳) - Bangladeshi Taka' },
  { value: 'BGN', label: 'BGN (лв) - Bulgarian Lev' },
  { value: 'BHD', label: 'BHD (.د.ب) - Bahraini Dinar' },
  { value: 'BIF', label: 'BIF (FBu) - Burundian Franc' },
  { value: 'BMD', label: 'BMD ($) - Bermudian Dollar' },
  { value: 'BND', label: 'BND ($) - Brunei Dollar' },
  { value: 'BOB', label: 'BOB (Bs.) - Bolivian Boliviano' },
  { value: 'BSD', label: 'BSD ($) - Bahamian Dollar' },
  { value: 'BTN', label: 'BTN (Nu.) - Bhutanese Ngultrum' },
  { value: 'BWP', label: 'BWP (P) - Botswana Pula' },
  { value: 'BYN', label: 'BYN (Br) - Belarusian Ruble' },
  { value: 'BZD', label: 'BZD ($) - Belize Dollar' },
  { value: 'CDF', label: 'CDF (FC) - Congolese Franc' },
  { value: 'CLP', label: 'CLP ($) - Chilean Peso' },
  { value: 'COP', label: 'COP ($) - Colombian Peso' },
  { value: 'CRC', label: 'CRC (₡) - Costa Rican Colón' },
  { value: 'CUP', label: 'CUP ($) - Cuban Peso' },
  { value: 'CVE', label: 'CVE ($) - Cape Verdean Escudo' },
  { value: 'CZK', label: 'CZK (Kč) - Czech Koruna' },
  { value: 'DJF', label: 'DJF (Fdj) - Djiboutian Franc' },
  { value: 'DKK', label: 'DKK (kr) - Danish Krone' },
  { value: 'DOP', label: 'DOP ($) - Dominican Peso' },
  { value: 'DZD', label: 'DZD (د.ج) - Algerian Dinar' },
  { value: 'EGP', label: 'EGP (E£) - Egyptian Pound' },
  { value: 'ERN', label: 'ERN (Nfk) - Eritrean Nakfa' },
  { value: 'ETB', label: 'ETB (Br) - Ethiopian Birr' },
  { value: 'FJD', label: 'FJD ($) - Fijian Dollar' },
  { value: 'FKP', label: 'FKP (£) - Falkland Islands Pound' },
  { value: 'GEL', label: 'GEL (₾) - Georgian Lari' },
  { value: 'GIP', label: 'GIP (£) - Gibraltar Pound' },
  { value: 'GMD', label: 'GMD (D) - Gambian Dalasi' },
  { value: 'GNF', label: 'GNF (FG) - Guinean Franc' },
  { value: 'GTQ', label: 'GTQ (Q) - Guatemalan Quetzal' },
  { value: 'GYD', label: 'GYD ($) - Guyanese Dollar' },
  { value: 'HKD', label: 'HKD (HK$) - Hong Kong Dollar' },
  { value: 'HNL', label: 'HNL (L) - Honduran Lempira' },
  { value: 'HRK', label: 'HRK (kn) - Croatian Kuna' },
  { value: 'HTG', label: 'HTG (G) - Haitian Gourde' },
  { value: 'HUF', label: 'HUF (Ft) - Hungarian Forint' },
  { value: 'IDR', label: 'IDR (Rp) - Indonesian Rupiah' },
  { value: 'ILS', label: 'ILS (₪) - Israeli New Shekel' },
  { value: 'IQD', label: 'IQD (د.ع) - Iraqi Dinar' },
  { value: 'IRR', label: 'IRR (﷼) - Iranian Rial' },
  { value: 'ISK', label: 'ISK (kr) - Icelandic Króna' },
  { value: 'JMD', label: 'JMD ($) - Jamaican Dollar' },
  { value: 'JOD', label: 'JOD (د.أ) - Jordanian Dinar' },
  { value: 'KGS', label: 'KGS (сом) - Kyrgyzstani Som' },
  { value: 'KHR', label: 'KHR (៛) - Cambodian Riel' },
  { value: 'KMF', label: 'KMF (CF) - Comorian Franc' },
  { value: 'KPW', label: 'KPW (₩) - North Korean Won' },
  { value: 'KRW', label: 'KRW (₩) - South Korean Won' },
  { value: 'KWD', label: 'KWD (د.ك) - Kuwaiti Dinar' },
  { value: 'KYD', label: 'KYD ($) - Cayman Islands Dollar' },
  { value: 'KZT', label: 'KZT (₸) - Kazakhstani Tenge' },
  { value: 'LAK', label: 'LAK (₭) - Lao Kip' },
  { value: 'LBP', label: 'LBP (L£) - Lebanese Pound' },
  { value: 'LKR', label: 'LKR (Rs) - Sri Lankan Rupee' },
  { value: 'LRD', label: 'LRD ($) - Liberian Dollar' },
  { value: 'LSL', label: 'LSL (L) - Lesotho Loti' },
  { value: 'LYD', label: 'LYD (د.ل) - Libyan Dinar' },
  { value: 'MAD', label: 'MAD (د.م.) - Moroccan Dirham' },
  { value: 'MDL', label: 'MDL (L) - Moldovan Leu' },
  { value: 'MGA', label: 'MGA (Ar) - Malagasy Ariary' },
  { value: 'MKD', label: 'MKD (ден) - Macedonian Denar' },
  { value: 'MMK', label: 'MMK (K) - Myanmar Kyat' },
  { value: 'MNT', label: 'MNT (₮) - Mongolian Tögrög' },
  { value: 'MOP', label: 'MOP (P) - Macanese Pataca' },
  { value: 'MRU', label: 'MRU (UM) - Mauritanian Ouguiya' },
  { value: 'MVR', label: 'MVR (Rf) - Maldivian Rufiyaa' },
  { value: 'MWK', label: 'MWK (MK) - Malawian Kwacha' },
  { value: 'MXN', label: 'MXN ($) - Mexican Peso' },
  { value: 'MYR', label: 'MYR (RM) - Malaysian Ringgit' },
  { value: 'MZN', label: 'MZN (MT) - Mozambican Metical' },
  { value: 'NAD', label: 'NAD ($) - Namibian Dollar' },
  { value: 'NIO', label: 'NIO (C$) - Nicaraguan Córdoba' },
  { value: 'NOK', label: 'NOK (kr) - Norwegian Krone' },
  { value: 'NPR', label: 'NPR (Rs) - Nepalese Rupee' },
  { value: 'NZD', label: 'NZD (NZ$) - New Zealand Dollar' },
  { value: 'OMR', label: 'OMR (ر.ع.) - Oman Rial' },
  { value: 'PAB', label: 'PAB (B/.) - Panamanian Balboa' },
  { value: 'PEN', label: 'PEN (S/.) - Peruvian Sol' },
  { value: 'PGK', label: 'PGK (K) - Papua New Guinean Kina' },
  { value: 'PHP', label: 'PHP (₱) - Philippine Peso' },
  { value: 'PLN', label: 'PLN (zł) - Polish Zloty' },
  { value: 'PYG', label: 'PYG (₲) - Paraguayan Guaraní' },
  { value: 'QAR', label: 'QAR (ر.ق) - Qatari Riyal' },
  { value: 'RON', label: 'RON (lei) - Romanian Leu' },
  { value: 'RSD', label: 'RSD (дин.) - Serbian Dinar' },
  { value: 'RUB', label: 'RUB (₽) - Russian Ruble' },
  { value: 'RWF', label: 'RWF (FRw) - Rwandan Franc' },
  { value: 'SBD', label: 'SBD ($) - Solomon Islands Dollar' },
  { value: 'SCR', label: 'SCR (SR) - Seychellois Rupee' },
  { value: 'SDG', label: 'SDG (SDG) - Sudanese Pound' },
  { value: 'SEK', label: 'SEK (kr) - Swedish Krona' },
  { value: 'SGD', label: 'SGD (S$) - Singapore Dollar' },
  { value: 'SHP', label: 'SHP (£) - Saint Helena Pound' },
  { value: 'SLL', label: 'SLL (Le) - Sierra Leonean Leone' },
  { value: 'SOS', label: 'SOS (Sh) - Somali Shilling' },
  { value: 'SRD', label: 'SRD ($) - Surinamese Dollar' },
  { value: 'SSP', label: 'SSP (£) - South Sudanese Pound' },
  { value: 'STN', label: 'STN (Db) - São Tomé Dobra' },
  { value: 'SYP', label: 'SYP (LS) - Syrian Pound' },
  { value: 'SZL', label: 'SZL (L) - Swazi Lilangeni' },
  { value: 'THB', label: 'THB (฿) - Thai Baht' },
  { value: 'TJS', label: 'TJS (SM) - Tajikistani Somoni' },
  { value: 'TMT', label: 'TMT (T) - Turkmenistan Manat' },
  { value: 'TND', label: 'TND (د.ت) - Tunisian Dinar' },
  { value: 'TOP', label: 'TOP (T$) - Tongan Paʻanga' },
  { value: 'TRY', label: 'TRY (₺) - Turkish Lira' },
  { value: 'TTD', label: 'TTD ($) - Trinidad/Tobago Dollar' },
  { value: 'TWD', label: 'TWD (NT$) - New Taiwan Dollar' },
  { value: 'TZS', label: 'TZS (TSh) - Tanzanian Shilling' },
  { value: 'UAH', label: 'UAH (₴) - Ukrainian Hryvnia' },
  { value: 'UGX', label: 'UGX (USh) - Ugandan Shilling' },
  { value: 'UYU', label: 'UYU ($) - Uruguayan Peso' },
  { value: 'UZS', label: 'UZS (so\'m) - Uzbekistan Som' },
  { value: 'VES', label: 'VES (Bs.S) - Venezuelan Bolívar' },
  { value: 'VND', label: 'VND (₫) - Vietnamese Dong' },
  { value: 'VUV', label: 'VUV (VT) - Vanuatu Vatu' },
  { value: 'WST', label: 'WST (WS$) - Samoan Tala' },
  { value: 'XAF', label: 'XAF (FCFA) - Central African CFA' },
  { value: 'XCD', label: 'XCD ($) - East Caribbean Dollar' },
  { value: 'XOF', label: 'XOF (CFA) - West African CFA' },
  { value: 'XPF', label: 'XPF (₣) - CFP Franc' },
  { value: 'YER', label: 'YER (﷼) - Yemen Rial' },
  { value: 'ZMW', label: 'ZMW (ZK) - Zambian Kwacha' },
  { value: 'ZWL', label: 'ZWL ($) - Zimbabwean Dollar' },
];

export const POS_CART_KEY = 'zeneva_pos_cart';
export const POS_CUSTOMER_KEY = 'zeneva_pos_customer';
export const POS_TAX_RATE_KEY = 'zeneva_pos_tax_rate';
export const POS_DISCOUNT_KEY = 'zeneva_pos_discount';
export const POS_PAYMENT_METHOD_KEY = 'zeneva_pos_payment_method';
export const POS_AUTO_PRINT_KEY = 'zeneva_pos_auto_print';
export const QUEUED_ACTIONS_KEY = 'zeneva_offline_queue';
export const USER_PROFILE_KEY = 'zeneva_user_profile';
export const BUSINESS_INSTANCE_KEY = 'zeneva_business_instance';
export const POS_HELD_SALES_KEY = 'zeneva_pos_held_sales';
