/**
 * Delete the production service worker before `next dev` starts.
 *
 * next-pwa is disabled in development, but it does not clean up after itself.
 * `npm run build` writes `public/sw.js` plus a `workbox-*.js` runtime, and the
 * dev server then happily serves those static files. The worker precaches the
 * *built* app chunks, so localhost keeps answering from a bundle made before
 * your edits and the page looks like your changes reverted.
 *
 * The tell is a stack-trace line number that does not match the source, or —
 * worse, because it looks like a code problem — a feature you just finished
 * appearing to roll back.
 *
 * These are gitignored build artifacts, regenerated by every build, so removing
 * them costs nothing. Runs as `predev`; npm invokes it automatically.
 *
 * `firebase-messaging-sw.js` and `sw-helpers.js` are tracked source files that
 * push notifications need. They are matched by neither pattern below — keep it
 * that way.
 */
import fs from 'fs';
import path from 'path';

const publicDir = path.join(process.cwd(), 'public');

if (fs.existsSync(publicDir)) {
  // Anchored so `firebase-messaging-sw.js` cannot match: next-pwa's own output
  // is exactly `sw.js`/`sw.js.map` and `workbox-<hash>.js`.
  const isArtifact = (name) =>
    name === 'sw.js' ||
    name === 'sw.js.map' ||
    /^workbox-[a-z0-9]+\.js(\.map)?$/i.test(name);

  const removed = [];
  for (const name of fs.readdirSync(publicDir)) {
    if (!isArtifact(name)) continue;
    try {
      fs.rmSync(path.join(publicDir, name));
      removed.push(name);
    } catch (err) {
      console.warn(`[predev] Could not remove public/${name}: ${err.message}`);
    }
  }

  if (removed.length) {
    console.log(
      `[predev] Removed stale PWA artifacts: ${removed.join(', ')}. ` +
      'If a page still looks stale, hard-reload once to drop the worker already in your browser.',
    );
  }
}
